@startuml Kitchen_Timer_State

state "カウント時間 設定モード" as SettingTime
state "カウントダウン中" as CountDown
state "カウントダウン ストップ中" as StopCountDown
state "カウントダウン 終了" as EndCountDown

[*] --> NonSetTime

NonSetTime --> SetTime



@enduml